#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon May 20 13:22:41 CEST 2024
# SW Build 4126759 on Thu Feb  8 23:52:05 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_alu_behav -key {Behavioral:sim_ALU:Functional:tb_alu} -tclbatch tb_alu.tcl -protoinst "protoinst_files/simpleComputer.protoinst" -view /home/juan/github/simpleComputer/xilinx_simpleComputer/tb_alu_behav.wcfg -log simulate.log"
xsim tb_alu_behav -key {Behavioral:sim_ALU:Functional:tb_alu} -tclbatch tb_alu.tcl -protoinst "protoinst_files/simpleComputer.protoinst" -view /home/juan/github/simpleComputer/xilinx_simpleComputer/tb_alu_behav.wcfg -log simulate.log

